### ISSUE TITLE
好像广西的都可以 (*^▽^*)

### ISSUE THREAD

**Issue by colflip** [CNawalol/qndxx-action#1]

**Comment by awalol** [comment]
真的可以吗？
我只是做来备用的，并没有实际使用过几次，我不确定老师那里会不会有记录。
我只是把网页版抓到的数据放进去而已。

**Comment by awalol** [comment]
这是网页版的[青年大学习](http://qndxx.bestcood.com/nanning/daxuexi)
希望您可以深入研究下。
谢谢

**Comment by colflip** [comment]
应该是可以的，因为编号是统一的。
不过，老师应该能够看到从哪个接口登录，其他地区的在南宁登录，会很奇怪。



在 2021-06-19 18:17:00，"CNawalol" ***@***.***> 写道：

这是网页版的青年大学习
希望您可以深入研究下。
谢谢
